### ISSUE TITLE
.... what I was looking for...

### ISSUE THREAD

**Issue by pacmenDE** [mr-whitefoot/ESP-Relay-Portal-Arduino#3]
hi mr-whitefoot,
Your project is similar to what I was looking for...
Can the relay also be time-controlled?
After the ESP01 is connected to the internet, can it pull the time from an ntp server and then turn on/off depending on the configured time?
Would you be willing to program this in? I would be willing to pay you for it too!

**Comment by mr-whitefoot** [comment]
Hello, pacmenDE.
Work in progress.

**Comment by mr-whitefoot** [comment]
Coming soon...
<img width="414" alt="image" src="https://github.com/mr-whitefoot/ESP-Relay-Portal/assets/16363451/68468eab-a7b1-488c-91c0-90d5e21f072c">

**Comment by mr-whitefoot** [comment]
https://github.com/mr-whitefoot/ESP-Relay-Portal/releases/tag/version_2.5.10
