### ISSUE TITLE
Reset WiFi credentials

### ISSUE THREAD

**Issue by sanbroz** [mr-whitefoot/ESP-Relay-Portal-Arduino#4]
Hi, add a option to reset Wifi Credentials, Now we are unable to change if we enter wrong Wifi password and SSID

**Comment by mr-whitefoot** [comment]
Hello, if device can't connect to wifi, because wrong wifi credentials for example, there have an option with wifi access point with name of your device(set in configuration) by default name is relayAp. When WiFi AP is active you can connect to it and change wifi configuration.

**Comment by mr-whitefoot** [comment]
Fixed AP mode in release [2.5.21](https://github.com/mr-whitefoot/ESP-Relay-Portal/releases/tag/version_2.5.21).
