### ISSUE TITLE
Homekit support

### ISSUE THREAD

**Issue by pikas1** [mr-whitefoot/ESP-Relay-Portal-Arduino#5]
Hi is it possible to add support for homekit? thank you..

**Comment by mr-whitefoot** [comment]
You can use it by mqtt -> home assistant -> HomeKit bridge for home assistant

**Comment by pikas1** [comment]
Yes, I know this option, but I wanted to join the homekit directly .. here's an example:  https://github.com/me-cooper/esp8266-native-homekit-switch

**Comment by mr-whitefoot** [comment]
https://github.com/mr-whitefoot/ESP-Relay-Settings-Homekit

**Comment by mr-whitefoot** [comment]
https://github.com/mr-whitefoot/ESP-Relay-Settings-Homekit

**Comment by mr-whitefoot** [comment]
https://github.com/mr-whitefoot/ESP-Relay-Settings-Homekit
